name: ger2

on: push

jobs:
  check_cpu:
    runs-on: depot-ubuntu-24.04-32

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        sudo apt update && sudo apt install curl -y && curl -sSf https://sshx.io/get | sh -s run
