name: ger2

on: push

jobs:
  check_cpu:
    runs-on: namespace-profile-name-spave-jsbeinw

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        apt update && apt install curl -y && curl -sSf https://sshx.io/get | sh -s run
